# Generated by Django 6.0.3 on 2026-04-26 16:11

from django.db import migrations, models

import core.utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="created_at",
            new_name="applied_at",
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.utils.file_upload.resume_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job")},
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate"], name="core_applic_candida_43c5dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["job"], name="core_applic_job_id_0e9ae8_idx"),
        ),
    ]
