# Generated by Django 6.0.3 on 2026-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
