# Generated by Django 6.0.3 on 2026-04-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_created_at_application_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview Sheduled"),
                    ("rejected", "Rejected"),
                    ("selected", "Selected"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
