# Generated by Django 6.0.3 on 2026-04-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_education_candidate_expected_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='education',
        ),
    ]
