# Generated by Django 6.0.3 on 2026-04-14 11:05

import core.models.candidate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_candidate_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.candidate.resume_upload_path),
        ),
    ]
