# Generated by Django 6.0.3 on 2026-04-14 12:24

import core.models.candidate
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.candidate.resume_upload_path, validators=[core.validators.validate_resume]),
        ),
    ]
