# Generated by Django 6.0.3 on 2026-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_applicationlog_application_savedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
