# Generated by Django 6.0.3 on 2026-05-28 19:26

import core.utils.file_upload
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_application_status_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.file_upload.resume_upload_path, validators=[core.validators.validate_resume]),
        ),
    ]
