# Generated by Django 6.0.3 on 2026-06-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_application_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
