# Generated by Django 6.0.3 on 2026-06-11 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('introduction', 'Introduction'), ('experience', 'Experience'), ('skills', 'Skills'), ('availability', 'Availability'), ('salary', 'Salary')], max_length=30)),
                ('question', models.TextField()),
                ('is_follow_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_index', models.IntegerField(default=0)),
                ('current_category', models.CharField(blank=True, max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.aiinterviewsession')),
            ],
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questiontemplate'),
        ),
    ]
