# Generated by Django 6.0.3 on 2026-06-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_questiontemplate_interviewstate_aiquestion_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="expected_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="weight",
            field=models.FloatField(default=1),
        ),
    ]
