# Generated by Django 6.0.3 on 2026-07-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_errorlog_securitylog_audittrail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="qualification",
            field=models.CharField(default="Bachelor Degree", max_length=100),
            preserve_default=False,
        ),
    ]
