# Generated by Django 6.0.3 on 2026-07-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_job_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityslot",
            name="employer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_slots",
                to="core.employer",
            ),
            preserve_default=False,
        ),
    ]
