# Generated by Django 6.0.3 on 2026-07-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_paymenttransaction_subscriptionplan_billinghistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.usersubscription'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
