# Generated by Django 6.0.3 on 2026-07-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paymenttransaction_captured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_candidate_access',
            field=models.IntegerField(default=0),
        ),
    ]
