name: Django CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: zecpath_db
          POSTGRES_USER: zecpath_user
          POSTGRES_PASSWORD: Zecpath@321
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U zecpath_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd zecpath_backend
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Create .env
        run: |
          cd zecpath_backend
          echo "SECRET_KEY=test-secret-key" >> .env
          echo "DEBUG=True" >> .env
          echo "DB_NAME=zecpath_db" >> .env
          echo "DB_USER=zecpath_user" >> .env
          echo "DB_PASSWORD=Zecpath@321" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Run migrations
        run: |
          cd zecpath_backend
          python manage.py migrate

      - name: Django system check
        run: |
          cd zecpath_backend
          python manage.py check

  deploy:
    needs: build

    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            git fetch origin
            git checkout dev
            git pull origin dev

            source /venv/bin/activate

            pip install -r requirement.txt

            python manage.py migrate

            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn

            sudo systemctl status gunicorn --no-pager